# Generated by Django 4.1.3 on 2022-12-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordOfPaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('numoftimes', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=1000)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='paa.keywordofpaa')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_search', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_search', to='paa.keywordofpaa')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='paa.keywordofpaa')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordGoogleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_images', to='paa.keywordofpaa')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWordAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=1000)),
                ('keywordofpaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='paa.keywordofpaa')),
            ],
        ),
    ]
