# Generated by Django 4.1.3 on 2022-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordgoogleimages',
            name='image',
            field=models.TextField(),
        ),
    ]
