# Generated by Django 4.1.3 on 2022-12-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paa', '0002_alter_keywordgoogleimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordgoogleimages',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
